Removed dependencies on bfasst
byuccl/bfasst pull request #100
Opened 2022-11-14 18:31 UTC by JakeEdvenson

I'm preparing the tool to be put in a separate directory as a third_party tool rather than bfasst exclusive. Currently, it works as it's own folder, so these changes are a step in that direction.

2022-11-16 05:03 UTC, reillymck commented
Please do not request user input, use function parameters and command line arguments. I noticed this in a few files. Thanks.

2022-11-16 19:37 UTC, reillymck commented on scripts/bfasst/compare_waveforms/compare_waveforms.py
> +        default=0,
Set the default to 100 here.

2022-11-21 18:15 UTC, reillymck commented
Good addition with the tests. Please incorporate my previous comment, and then I will merge.

2022-11-21 18:18 UTC, JakeEdvenson commented
@reillymck I might be missing something, but I believe I did incorporate your last comment. Default should be set to 100 now and user input shouldn't be requested anymore.

2022-11-21 18:20 UTC, reillymck commented
I left a comment directly on waveform.py

2022-11-21 18:34 UTC, JakeEdvenson commented
@reillymck I've looked through the waveform.py file and all previous commits with it, I'm not seeing any comments. The only comment I've seen directly on a file in this PR is this one here (which should be resolved):
![image](https://user-images.githubusercontent.com/77412657/203132400-6fb7662f-600a-46cc-ad95-e10310208f6c.png)

On the main page, I only see your comment about user input, the direct comment on compare_waveform.py, your comment 18 minutes ago, and your response.
Should I be looking somewhere else?

2022-11-21 18:58 UTC, JakeEdvenson commented
@reillymck Is there another way to view comments aside from this?
![image](https://user-images.githubusercontent.com/77412657/203137159-11d55e4e-ac3f-4306-9395-d5feacf30fe6.png)

2022-11-21 19:17 UTC, reillymck requested changes

2022-11-21 19:17 UTC, reillymck commented on scripts/bfasst/compare/waveform.py
> +        for k in design_props.keys():
Last thing:
```python
return ("included_all_verilog_files" in design_props) or ("include_all_system_verilog_files" in design_props)
```
This should replace lines 106-115

2022-11-21 19:18 UTC, reillymck commented
Is it visible now?

2022-11-22 04:06 UTC, reillymck approved these changes

2022-11-22 04:06 UTC, merged