Pablo designs
byuccl/bfasst pull request #105
Opened 2023-02-04 03:36 UTC by palm9727

Just opening a pull request to see the things I need to change.

2023-03-10 22:30 UTC, reillymck requested changes

2023-03-11 01:41 UTC, palm9727 commented on scripts/bfasst/netlist_mapping/README.md
> +REAd MApped Points mapped_points.txt
Yes

2023-03-11 01:47 UTC, palm9727 commented on scripts/bfasst/netlist_mapping/README.md
> +$ python ccl_mapping.py netlist_examples/tx_impl.v netlist_examples/tx_reversed.v > mapped_points.txt
Done

2023-03-11 01:49 UTC, palm9727 commented on scripts/bfasst/netlist_mapping/functional/qm.py
> +#!/usr/bin/env python
Most likely. I just didn't know how to do it so I added qm.py as part of my code.

2023-03-11 01:51 UTC, palm9727 commented on scripts/bfasst/netlist_mapping/functional/converter.py
> +"""This file contains functions used to transform numbers between hex and binary"""
I just though it would be faster to build the functions that do exactly what I wanted.

2023-03-17 16:49 UTC, jgoeders commented
@palm9727 @reillymck Is this ready to be merged now?

2023-03-23 22:06 UTC, merged