updated README to correct errors
byuccl/bfasst pull request #177
Opened 2023-05-08 15:31 UTC by KeenanRileyFaulkner

…ke branch for install

The use of make branch is temporary, until Reilly can update main branch makefiles to match

2023-05-08 16:03 UTC, jgoeders requested changes

2023-05-08 16:03 UTC, jgoeders commented on README.md
> +Information found here: https://github.com/chipsalliance/f4pga-xc-fasm2bels/blob/master/README.md
Can you add < > around the link?

2023-05-08 16:03 UTC, jgoeders commented on README.md
>  ### Yosys
Can you add a section like this for rapidwright?

2023-05-08 16:03 UTC, jgoeders commented on README.md
> +An open source synthesis tool. https://github.com/YosysHQ/yosys/blob/master/README.md
Add < > around link

2023-05-08 16:23 UTC, KeenanRileyFaulkner commented on README.md
>  There are also several pre-configured *experiments*, which allow you to run a large set of designs and collect results.  These configurations are located within the `experiments` directory, and can b
Done

2023-05-08 16:23 UTC, KeenanRileyFaulkner commented on README.md
> +  * ```git checkout make```
Done

2023-05-08 16:24 UTC, KeenanRileyFaulkner commented on README.md
> +  * ```git checkout main```
Done

2023-05-08 16:24 UTC, KeenanRileyFaulkner commented on README.md
> +Information found here: https://github.com/chipsalliance/f4pga-xc-fasm2bels/blob/master/README.md
Done

2023-05-08 16:24 UTC, KeenanRileyFaulkner commented on README.md
> +    * This tool depends on Project X-Ray (also installed with bfasst): https://github.com/f4pga/prjxray/blob/master/README.md
Done

2023-05-08 21:19 UTC, jgoeders commented
@KeenanRileyFaulkner It looks like Reilly already updated the Makefile as part of #173.  Can you resolve this conflict and see which of your edits are still needed? Thanks!!

2023-05-10 15:03 UTC, KeenanRileyFaulkner commented
I looked through the conflict and resolved it. The new README should have the correct path for /designs rather than /examples, <> around links, a section for RapidWright docs, and correct information on Fasm2Bels

2023-05-10 15:05 UTC, jgoeders requested changes

2023-05-10 15:08 UTC, merged